name: Open Journal bibtex references validation
description: "Validate paper's bibtex references"
inputs:
  issue_id:
    description: The review issue id for the paper
    required: true
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Clone repository
      shell: bash
      run: |
        [[ "${{ inputs.branch }}" == "" ]] && (git clone --single-branch ${{ inputs.repository_url }} . ) || (git clone --single-branch --branch ${{ inputs.branch }} ${{ inputs.repository_url }} .)
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1
        bundler-cache: true
        cache-version: bibtex-checks
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Check bibtex references
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/check_references.rb

branding:
  icon: check-circle
  color: blue
